- src/android/com/adobe/phonegap/push/PushPlugin.java
> Notifications should persist when the app is moved to the background in order to draw the user back to re-activate the app when they are done multitasking.
>
> Notifications should be destroyed when the all is closed though to avoid clutter.
> breaking(android): move clearAllNotifications to destroy from pause

- plugin.xml
* https://developer.android.com/studio/build/multidex
> Multidex support for Android 5.0 and higher
>
> Android 5.0 (API level 21) and higher uses a runtime called ART which natively supports loading multiple DEX files from APK files. ART performs pre-compilation at app install time which scans for classesN.dex files and compiles them into a single .oat file for execution by the Android device. **Therefore, if your minSdkVersion is 21 or higher multidex is enabled by default, and you do not need the multidex support library.**
By default, `cordova-android` 9.x defines the `minSdkVersion` as `22` by default. 
This plugin support `cordova-android >= 9.x`.
> breaking(android): drop phonegap-plugin-multidex dependency

- plugin.xml
This bumps the com.android.support:support-v13 to version 28.0.0 which is the latest and last release that will be released for the Android Support Library.
Any newer versions would require AndroidX.
> chore(android): bump com.android.support:support-v13:28.0.0

- docs/INSTALLATION.md
- plugin.xml
- src/android/com/adobe/phonegap/push/PushInstanceIDListenerService.java
This bumps the Android's Firebase Cloud Messaging version to 18.+.
This is the latest and last version that supports the Android Support Libraries.
> breaking(android): bump fcm@18.+

- docs/INSTALLATION.md
- hooks/browser/updateManifest.js
- package-lock.json
- package.json
- plugin.xml
closes: #17 
This plugin is going to be scoped in the npmjs registry.
When installing this plugin, once released, the command would be:
```bash
cordova plugin add @havesource/cordova-plugin-push
```
Since the initial plugin release will support Cordova CLI `>= 9.0.0`, not all areas can be properly scoped. (E.g. `plugin.xml` etc)
This means to remove the plugin, the following command must be used:
```bash
cordova plugin rm havesource-cordova-plugin-push
```
As you notice, the plugin name is not scoped in this case.
I am also planning to release 2.x shortly after 1.x. The goal of 2.x is to start support from Cordova CLI >= 10.0.0.
Cordova 10 provides full support of scoped packages. This means the adding and removing command would use the scopped key `@havesource/cordova-plugin-push`
A few …
> chore(npm): properly configure for scope package

- plugin.xml
Plugin cannot be installed in parallel w/ https://github.com/chemerisuk/cordova-plugin-firebase-analytics because of incompatible Firebase SDK versions.
As proposed by @rdesimone https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/167#issuecomment-704920606 I updated the version. Both plugins can not be installed at the same time.
#41 
We need to use both plugins in the same customer app.
Updated framework version, cleaned my cordova project, re-added platforms, build app, installed app on iOS and Android test devices, allowed them to receive push notifications, send notification to test devices.
cleaning steps
1. rm -rf node_modules
2. rm -rf platforms
3. rm -rf plugins
4. pod repo update
5. npm install --no-optional
6. npm cordova platform rm android
7. npm cordova …
> feat(ios): increase firebase framework to 6.32.2

- src/android/com/adobe/phonegap/push/PushPlugin.java
Change the default channel name to the app name.
[phonegap#2691](https://github.com/phonegap/phonegap-plugin-push/issues/2691)
_(Hope it is okay to link to issues in the original plugin instead of opening one here.)_
The default channel name on android is `PhoneGap PushPlugin`.
This name is visible e.g. in the notification settings of the app, which could be confusing.
To prevent this the user would be required to create a channel with a custom name.
Instead of this the plugin could also provide a better default e.g. the app name.
Tested on multiple android devices.
_(Already used this in production in a fork of the original plugin.)_
> fix(android): Use app name for default channel

- README.md
- docs/INSTALLATION.md
- types/index.d.ts
Cleanup docs to fit this repo & plugin
n/a
Cleanup with accurate information
n/a
n/a
> doc: cleanup docs

- docs/INSTALLATION.md
- package.json
- plugin.xml
Set the Cordova Android requirement to `>= 8.0.0` for this short lived release.
closes #36
For the initial, short lived, release, we will continue to support `cordova-android >= 8.0.0`. This will be only for the first release major 1.x.
Starting from the second major release, 2.x, the `cordova-android` requirements will be set back to `>=9.0.0`. Anyone who can not use Cordova-Android 9.x or greater will be locked in to 1.x major release.
n/a
> chore(android): set requirement >= 8.0.0

- docs/API.md
Document missing API property, `lightColor`, which is used to enable and set the notification light for Android
closes #16
Keep documents up-to-date
n/a
> doc(android): enable & set notification light with lightColor

- src/android/com/adobe/phonegap/push/PushPlugin.java
Fixes missing channel description causing Android app to crash.
* This PR also created the `getAppName` method to centralize the code that has been used in 3 areas of the class to get the app name.
n/a
Instead of crashing the app when the user forgets to add a channel description, have it fallback to the app's name.
Even though the channel description property is a required field, I feel it would be safer to fall back to the app name so that the app wont crash because the user forgot to add a custom description. 
First I created a blank hello world app with a new channel
```js
PushNotification.createChannel(
() => { console.log('success'); },
() => { console.log('error'); },
{
id: 'test'
}
);
```
At this stage without the PR:
* Confirmed that the app crashes without the description
After, …
> fix(android): missing channel description crash

- .github/workflows/ci.yml
Use latest GitHub Action related dependencies.
> ci: bump gh-action related dependencies

- docs/INSTALLATION.md
- package.json
- plugin.xml
Bump Cordova-iOS Requirement to `>=6.0.0`
> breaking: ios requirement bump

- plugin.xml
Allow the iOS Firebase/Messaging dependency version to be overridable.
N/A
- `cordova plugin add github:havesource/cordova-plugin-push\#feat/ios-dep-override`
- Reviewed the Podfile to ensure the default "~> 6.32.2" is set.
- `cordova plugin add github:havesource/cordova-plugin-push\#feat/ios-dep-override --variable IOS_FIREBASE_MESSAGING_VERSION="~> 6.31.0"`
- Reviewed the Podfile to ensure that "~> 6.31.0" is set.
- Will be handled in a seperate PR as there will be a refactor of the install docs.
> feat(ios): support firebase/messaging dep version override

- docs/TYPESCRIPT.md
Update the `import` in the Typescript docs to use the new `@havesource/cordova-plugin-push` package name.
n/a, just a small docs fix
When using the docs as-is, people will use the types from the previous package, which could even cause issues as that probably won't be installed.
Successfully used that new import in my own project.
n/a
> docs(typescript): update TS type import to new package name

- .eslintrc.yml
- example/server/pushADM.js
- example/server/pushAzure.js
- package-lock.json
- package.json
- src/js/push.js
- www/push.js
Update eslint
none
Fix npm audit for devlopment
`npm t`
> dep(dev): bump @cordova/eslint-config@^4.0.0 w/ fixes

- docs/PAYLOAD.md
Fixing a typo in the push notification format tocs
there is a typo in the docs
I saw the preview
> fixing typo in docs

- src/android/com/adobe/phonegap/push/PushHandlerActivity.kt
Appears that during refactoring from Java to Kotlin, the returned value of`processPushBundle` was flipped.
When reading the code, I was expecting that the returned value was only `true` when the inline reply exists. This is determined if  `RemoteInput.getResultsFromIntent` was not null.
I expected this case because the variable name `inline`, but the variable name was not actually detailed enough to explain if it was `has` vs `notHave`.
Compaing with Java code, it appears that `true` is always returned even when there is no inline reply. So this means when Inline reply is set, then false is returned.
This PR should flip the case back and I also renamed the variable `inline` to `notHaveInlineReply` to properly explain what the return result represents.
fixes #149
Fixes the flipped return …
> fix(android): processPushBundle flipped returned value

- bower.json
The `bower.json` file contains a false license attribute. This change had already been fixed in `package.json` in 2017 in commit 4274d0759acd7110ed2592ed1d2ce3bf692711d3
closes #165
Signed-off-by: Nico Rikken <nico.rikken@alliander.com>
> chore: correct Bower metadata to MIT license

- docs/PLATFORM_SUPPORT.md
Update PLATFORM_SUPPORT.md to mention the supported cordova and platform versions for the 2.x and 3.x versions of the plugin.
The mentioned versions are based on the information in the `<engines>` tag in `plugin.xml` for versions `2.3.0` and `3.0.0`.
n/a, just a minor docs change.
The previous information was out of date.
n/a, just a docs change
n/a
> doc: add 2.x and 3.x to PLATFORM_SUPPORT.md

- plugin.xml
Added missing `android:exported="true"` flags for services that has `intent-filter`.
closes: #146
closes: #153
Follow documentation sepc: https://developer.android.com/guide/topics/manifest/service-element#exported
- `cordova build android`
- `cordova run android`
- Firebase Console Test Push Notification
> fix(android): add service exported flags w/ intent-filter

- plugin.xml
- src/ios/PushPlugin.h
- src/ios/PushPlugin.m
See PR #100 for description.
This PR cherry-picks the changes from #100 and applies the ticket comment suggestions. Also updates to use the new notification name/key `FIRMessagingRegistrationTokenRefreshedNotification`
Closes #100
Closes #84
> feat!(ios): update Firebase Messaging to ~> 8.1.1

- docs/INSTALLATION.md
- docs/PLATFORM_SUPPORT.md
- package-lock.json
- package.json
- plugin.xml
Bump cordova-android engine requirement
n/a
Since Android 13 (SDK 33) APIs are being added to the source code, we should increase the cordova-android requirement to `>=12.0.0` which supports SDK 33 minimum.
Anything lower will not build successfully out of the box.
plugin add
> feat(android)!: bump platform requirement cordova-android>=12.0.0

- src/android/com/adobe/phonegap/push/FCMService.kt
This is just a fix for a deprecation warning in the build process (deprecated in JAVA)
Changed from Html to HtmlCompat
> fix(android): deprecated warning Html.fromHtml

- src/ios/AppDelegate+notification.m
Fixed: on iOS, Callback function is not called when user click notification action where foreground: true
Resolves #101
Tested on iPhone 6s (iOS 14).
> fix(ios): callback not being called #101

- types/index.d.ts
Add the missing iOS specific`critical` to the TypeScript typings
According to the [API docs](https://github.com/havesource/cordova-plugin-push/blob/master/docs/API.md#ios) and the code a `critical` property is supported on iOS, but it is missing in the TypeScript typings. The PR adds it.
(https://github.com/havesource/cordova-plugin-push/issues/270)
Fixes TS compilation issues when using "critical" notifications on iOS.
Used the updated typings in my own test project
> fix(ios): add missing critical to typings

- src/android/com/adobe/phonegap/push/FCMService.kt
Fixes the issue where the notification was being clipped and the expand arrow was displayed.
Fixes #263
Closes #268
Resolves above issues
Tested on Android SDK 24 & 34
> fix(android): clipped notification text and expand arrow

- docs/API.md
- src/ios/PushPlugin.h
- src/ios/PushPlugin.m
- types/index.d.ts
- Remove unused methods & properties/variables
- Remove some of the deprecated code/defines/protocols of GCM
- This PR does not rename of variables
- Remove excessive newlines
- Cleanup formatting
Note: The `fcmSandbox` is an iOS option that replaced `gcmSandbox` in version 2.0.0 of the `phonegap-push-plugin` days, but when GCM was dropped, `fcmSandbox` did not actual configure anything. This option can be dropped since it was never used and also FCM automatically determines the environment type.
N/A
Cleanup code base
- Build and run app in simulator.
> chore(ios)!: remove unused & deprecated code & styling formatting

- plugin.xml
- src/ios/PushPlugin.m
- src/ios/PushPluginSettings.h
- src/ios/PushPluginSettings.m
Extract Push Plugin Settings
n/a
To extract and centralize logic related to creating and storing settings that are passed in from init process.
- Build
- Run simulator
- Drop APNs payload
- Included categories
> feat(ios): extract settings into PushPluginSettings

- plugin.xml
- src/ios/AppDelegate+notification.h
- src/ios/AppDelegate+notification.m
- src/ios/PushPlugin.h
- src/ios/PushPlugin.m
- src/ios/PushPluginFCM.h
- src/ios/PushPluginFCM.m
Closes #285
This PR would replace #285. This PR does not upgrade to 10.24.0 as #285 does but a separate PR would handle the version upgrade.
Extracts all FCM related logic to its own class.
Improve separation, maintainability, & encapsulation between FCM and non FCM code.
- Build
- Run on Simulator
- Drop APNs payloads
- Run on Device
- Pushed notification through FCM console
> feat(ios)!: extract FCM related logic to PushPluginFCM

- src/ios/PushPlugin.m
Fixes an issue where `setApplicationIconBadgeNumber` was not running on the main thread. When this method is called on the wrong thread, Xcode displays the following error, and the app may also crash.
This issue can be reproduced by setting the `clearBadge` property to `true` when initializing the Push Plugin.
```
Main Thread Checker: UI API called on a background thread: -[UIApplication setApplicationIconBadgeNumber:]
PID: 0000, TID: 0000, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   cordovaTest.debug.dylib             0x0000000000000000 __19-[PushPlugin init:]_block_invoke.54 + 208
5   libdispatch.dylib                   0x0000000000000000 _dispatch_call_block_and_release + 24
6   libdispatch.dylib                   0x0000000000000000 …
```
> fix(ios): run setApplicationIconBadgeNumber on main thread

- plugin.xml
- src/ios/CDVAppDelegate+notification.h
- src/ios/CDVAppDelegate+notification.m
- src/ios/PushPlugin.h
- src/ios/PushPlugin.m
- src/ios/PushPluginConstants.h
- src/ios/PushPluginConstants.m
- Start using `CDVAppDelegate` instead of `AppDelegate`
- Move logic to `PushPlugin.m`.
Resolves #252
Resolves #172
Closes #186
- Follow Cordova standards
- Centralize plugin login
- Tested APNS Payload drops
> feat(ios)!: migrate to CDVAppDelegate and move logic to PushPlugin.m

- src/ios/PushPlugin.m
**Updated `didReceiveNotificationResponse`:**
- Removed setting of `actionCallback` to `response.actionIdentifier`.
- Removed logic in the `UIApplicationStateInactive` state that decided whether to set the launch notification to the modified or unmodified `userInfo` containing the `response.actionIdentifier` on `actionCallback`.
- Added `applicationState` to `userInfo`, which is later used to decide whether `actionCallback` will be removed from the payload sent to the front end. See `notificationReceived` for reference.
- Since `applicationState` is now appended to `userInfo`, we can pass it up to the front on the `notification` event.
- Note: I am currently removing it from the payload before returning, as we should confirm whether we can match this behavior on Android.
**Updated …
> fix(ios): on notification event payload & stop background task

- src/ios/PushPlugin.m
In iOS 18.0, there is a known issue where the `willPresentNotification` method is triggered twice for a single payload. 
The `willPresentNotification` method is normally triggered when a notification is received while the app is in the foreground.
Due to this bug, the notification payload is delivered twice, causing the front-end to process the notification event twice as well.
This behavior is unintended, so this PR added a block of code to check if the payload is a duplicated by comparing the payload content and the timestamp of when it was received.
**Note:** This block of code will only run on iOS 18.0. When testing the iOS 18.1 official release, the bug seems to be resolved.
Resolves #295
This PR proposes a solution to address the iOS 18.0 notification duplication bug.
The fix adds a …
> fix(ios)!: duplicate notification presentation on iOS 18.0

- plugin.xml
- src/ios/AppDelegate+PushPlugin.h
- src/ios/AppDelegate+PushPlugin.m
- src/ios/PushPlugin.m
Reverting to an `AppDelegate` extension instead of `CDVAppDelegate`.
It seems that converting to a `CDVAppDelegate` extension didn't work as expected when other plugins were installed that also defined their own `AppDelegate` extensions with methods required by this plugin.
For example, `cordova-plugin-firebasex`.
n/a
Reverting back `AppDelegate`. See the "Description" section for context.
Created a project with `cordova-plugin-firebasex` to confirm that the methods defined in this plugin are triggered again.
> chore: revert back to AppDelegate

- types/index.d.ts
Add missing `clearNotification` to typescript definitions.
Resolves #85 
n/a
> fix: add clearNotification to typescript definitions

- src/android/com/adobe/phonegap/push/FCMService.kt
Set the `xfermode` after the circle is drawn so that the source bitmap is clipped correctly inside the circle.
Previously, the `xfermode` was applied during the creation of the paint object, which caused a timing issue. As a result, the image was not clipped inside the circle properly, making it appear as though there was no image.
Resolves #199 
Fix the issue where `getCircleBitmap` was not displaying the image correctly.
- Build app
- Tested pushing payload before and after changes
Payload contained
- `image` pointing to a square image on web (square so I can confirm the circle effect)
- `image-type` set to `circle`
I also tried without setting the `image-type` to confirm default behavior.
> fix(android): getCircleBitmap not displaying image

- src/ios/PushPlugin.m
Update to make sure that `notificationMessage` is correctly storing an `NSDictionary`.
Create a mutable copy when the content needs to be updated and then restore an immutable copy.
Resolves #314
Closes #315
Fix issue reported in #314 to prevent app crashes.
Deployed app to iOS 18.1 device.
Pushed payload from AWS Pinpoint:
```json
{
"APNSMessage": {
"aps": {
"alert": "Sample message for iOS endpoints",
"content-available": "1"
}
}
}
```
Pushed payload from Amazon SNS
```json
{
"APNS_SANDBOX": "{\"aps\":{\"alert\":\"Sample message for iOS development endpoints\", \"content-available\": \"1\"}}"
}
```
Push plugin was initialized with the following:
```javascript
const push = PushNotification.init({
ios: {
alert: true,
badge: true,
sound: true
}
});
```
> fix(ios): make sure notificationMessage is immutable

- src/ios/PushPlugin.m
Reset flags and stored message after the received notification is processed and sent to the "notification" event.
Resolves #316
Fix issue where the notification event always displays `coldstart` as `false`.
Built app and sent a test notification push while app is open, closed, or in background.
Tested with most basic payload:
```json
{
"aps": {
"alert": "Sample message"
}
}
```
Results:
App Foreground:
```json
{
"message": "Sample message",
"additionalData": {
"foreground": true,
"coldstart": false
}
}
```
App Background (Tapped on Notification Banner):
```json
{
"message": "Sample message",
"additionalData": {
"foreground": false,
"coldstart": true
}
}
```
App Closed (Tapped on Notification Banner):
```json
{
"message": "Sample message",
"additionalData": {
"foreground": false, …
```
> fix(ios): reset flags & stored message after processing notification received

- src/ios/PushPluginFCM.m
Exclude configure if FirApp is already configured by an other library/
Using your package, especially your latest release 5.0.0, I encountered an error with Firebase being already configured. I used the FirApp verification from an other Cordova Plugin, tested it in my project and it works great.
> fix(ios): exclude configure if FirApp is already configured

- src/android/com/adobe/phonegap/push/PushPlugin.kt
Prevent second permission dialog from appearing on second launch if user already selected "Don't allow".
If the user selects "Don't allow" for the push notification permission, it is expected that the notification dialog will not reappear on subsequent launches asking the same question.
It is assumed that the user's decision reflects their intent.
If they made a mistake, they can go to the app settings to manually enable the permission.
Additionally, the unusual behavior of the permission dialog reappearing occurs only on the second launch; on the third or later launches, the dialog does not appear.
The changes in this PR ensure that the decision made by the app user is acknowledged and the permission will not be requested again.
This behavior was achieved by adding a call to …
> fix(android): prevent permission dialog appearing when already denied

- src/ios/PushPlugin.m
Fix the placement of when the reset flags are applied. And update of #319
Move the reset flags into the condition when notificationMessage and callbackId exists.
n/a
Tested pushing a payload in all states (background, foreground, inactive).
Confirmed that the `coldstart` and `foreground` flags continue to display correctly in payload.
> fix(ios): update reset flags placement in notificationReceived

- src/ios/PushPlugin.m
- src/ios/PushPluginSettings.m
Fix an accidental breaking property name change from `callback` to `identifier`.
Fix issue where category's `callback` was not being property set and triggered.
In the documentation and typings, the `CategoryActionData` object should include a key named `callback`.
On iOS, the native code refers to `callback` as `identifier`. Because of this, the native implementation was mistakenly modified to extract the `callback` value using the incorrect key `identifier`.
This PR reverts the key back to `callback` to align with the documentation and typings.
The issue was discovered during testing of the typings.
Updated code to make sure that the actionCallback is not removed in cases where the value is not default.
n/a
- Confirmed that the `callback` is triggered when clicking the category option. …
> fix(ios): revert accidental change to category "callback"

- src/android/com/adobe/phonegap/push/PushPlugin.kt
Resolve "PushPlugin.kt:616:13 Unresolved reference: ActivityCompat"
Added missing import for `androidx.core.app.ActivityCompat`
n/a
Reported in comment: https://github.com/havesource/cordova-plugin-push/pull/325#issuecomment-2529506217
Created blank android project, added plugin, and run build.
- confirmed issue without PR changes
- confirmed that the issue has been was resolved with PR changes
> fix(android): add missing import androidx.core.app.ActivityCompat

- src/ios/PushPlugin.m
Prevents the notification from triggering the notification event on app reload when a notification message exists.
Added the `isInitialized` flag as an additional parameter to determine if the app should trigger the `notificationReceived` method.
When the app launches and initializes for the first time, if a `notificationMessage` exists, it should be processed. This handles the case of tapping/opening a notification from the notification drawer while the app is inactive (closed/terminated).
If a notification is delivered and the app is reloaded using `window.location.reload()`, the plugin's `init` method is triggered again. This causes the `on('notification')` event to be triggered because the `notificationMessage` exists, which is incorrect behavior. The event should only be triggered by …
> fix(ios): dont trigger notificationReceived on app reload

- src/ios/PushPlugin.m
Fix an issue where the `notification` event payload's property `additionalData.foreground` is incorrectly set when the app is in the foreground and the `forceShow` option is enabled.
- Renamed the internal variable `isInline` to `isForeground`.
- Corrected the setting of `isForeground` in `didReceiveNotificationResponse` when the application state was `UIApplicationStateActive`. This should have been and is now set to `YES`.
- Explicitly define and set the `isForeground` to `NO` in the `didReceiveNotificationResponse` method when the application state is `UIApplicationStateInactive`.
n/a
Built an application and tested the following:
**`foreShow = true` Test Case:**
- AppState: Foreground
- `payload.additionalData.foreground` = `true`
- `payload.additionalData.coldstart` = `false`
- …
> fix(ios): correctly set foreground flag when forceShow is enabled

- src/android/com/adobe/phonegap/push/PushPlugin.kt
- Override CordovaPlugin.pluginInitialize()
- Remove calling super method
N/A
Now, `CordovaPlugin.initialize()` is deprecated at Cordova-android@v14.0.0.
refs https://github.com/apache/cordova-android/pull/1771
Following [cordova-docs](https://github.com/apache/cordova-docs/pull/1387), use `pluginInitialize` and remove calling super method.
N/A
> fix(android): initialize

- plugin.xml
We had an external audit to our App which uses this plugin.
During the audit, it was found that the activity "com.adobe.phonegap.push.BackgroundHandlerActivity" is
configured with the following permissions: `com.seamlink.gatewaybox.chporto.permission.BackgroundHandlerActivity [android:exported=true]` and that this allows other applications running on the device to access and interact with this Activity. This can become serious if this Activity contains sensitive features or information.
It was recomended that we configure the permissions protection level to "signature", because the Activity should only be accessed by applications with the same signature or certificate.
Changed the protection level of BackgroundHandlerActivity to only be used by applications with the same signature or …
> fix(android): add BackgroundHandlerActivity protectionLevel signature

- src/android/com/adobe/phonegap/push/PushPlugin.kt
Do not use ringtone to control notification audio
Resolves #40
Fix issue where notification was being controlled by ringtone
Built app and tested push noticiation
> fix(android)!: notification audio not to be controlled by ringtone
