package.json
Removes:
* `install`
* `pluginpub`
=> cleanup: remove unused dependencies

.github/workflows/ci.yml, .gitignore, package-lock.json, package.json
Add GitHub Actions CI Workflow
=> ci(gh-actions): add workflow

www/push.js
This just pushes an updated `www/push.js` which was forgotten
=> chore: add missing build of push.js

.github/config.yml, .github/lock.yml, .github/no-response.yml, .github/stale.yml
=> chore: update ticket management

docs/INSTALLATION.md, plugin.xml, src/ios/PushPlugin.m
Use the latest `Firebase/Messaging` library.
=> core(ios): use latest firebase library

hooks/browser/updateManifest.js
=> Corrected path to browser manifest file.

docs/PAYLOAD.md, plugin.xml, src/android/com/adobe/phonegap/push/BackgroundHandlerActivity.java, src/android/com/adobe/phonegap/push/PushConstants.java, src/android/com/adobe/phonegap/push/PushHandlerActivity.java
This PR is a cherry-pick of https://github.com/phonegap/phonegap-plugin-push/pull/2369
Full description can be seen in the above PR and the associated original ticket: https://github.com/phonegap/phonegap-plugin-push/issues/2364
closes #30
Ticket Request
- n/a
- n/a
**From Original PR**
**From Original PR**
**Additional Changes**
I updated the original PR's Android src code to follow new syntax.
=> feature: android notification data pass

package-lock.json
Rebuilt `package-lock.json`
n/a
Remove sub-dependency warning on `dot-prop`.
n/a
=> chore(npm): rebuilt package-lock.json

package-lock.json, package.json, plugin.xml
=> chore: bump version to 2.0.0-dev.0

plugin.xml
Force to use the cocoapod's CDN as source.
This PR will be rebased and merged after PR #47 is merged.
n/a
- `cordova plugin add`
n/a
=> feat(ios): force cocoapods cdn

src/android/com/adobe/phonegap/push/FCMService.java
closes #68
See closing ticket for more details.
This PR only cherry-picks the useful commit.
N/A
N/A
=> chore(android): remove duplicate code

.github/CONTRIBUTING.md
Changed "Codde" -> "Code" in the contributing docs
Seems like overkill to do this for this particular change, but I can create one if really needed.
Small typo in docs - the word code will be spelled correctly
N/A - docs only change
=> docs: fixed minor typo

.travis.yml, README.md
Remove old travis ci configs
N/A
This project is not using Travis CI
N/!
=> ci: remove old travis configs

README.md
Add GitHub Actions Results to README
N/A
Reporting
N/A
=> ci: add gh-actions badge to readme

plugin.xml
=> fix(android): PushHandlerActivity permissions regression

.github/workflows/ci.yml
Update CI Workflow
n/a
Use latest workflow dependencies and run on node 18.
See Action Run
=> ci: bump github action workflow and dependencies

example/server/pushADM.js, package-lock.json, package.json, src/js/push.js, www/browser/push.js, www/push.js
Bump devDependencies to resolve npm audits
n/a
Remove npm audit warnings in development environment.
`npm audit`
=> dep(npm): bump all devDependencies

plugin.xml
Bump GradlePluginGoogleServicesVersion to 4.3.15
Use latest GradlePluginGoogleServices and match with Cordova-Android 12.
`cordova plugin add` & `cordova build android`
=> feat(android): bump GradlePluginGoogleServicesVersion to 4.3.15 (match w/ Cordova-Android@12.x)

plugin.xml
Upgrade Gradle Plugin Kotlin requirement.
Resolves #224
Match the requirement of Cordova-Android 12.x
`plugin add` and `build android`
=> feat(android): bump gradle plugin kotlin to 1.7.21

package-lock.json, www/push.js
=> dep: resolve npm audit with rebuilt package-lock & rebuilt push.js with new packages

src/ios/AppDelegate+notification.m, src/ios/PushPlugin.m
Prefix all NSLog messages with `[PushPlugin]`
To make it clear to an end which is our NSLog messages vs NSLog message that might be printed by other plugins.
Build and simulator run test
=> chore(ios): update all NSLog to include [PushPlugin] prefix

plugin.xml
Updated default Firebase Messaging to 10.24.0
N/A
- Use newer Firebase Messaging library.
- Has Privacy Manifest defined
- Built App on Simulator
- Tested APNS Payload
- Build App on Physical Device (AdHoc Build)
- Tested FCM by pushing notification from Firebase Console
=> feat!(ios): bump firebase 10.24.0

docs/INSTALLATION.md, docs/PLATFORM_SUPPORT.md
Small doc cleanup and adding 5.0.0 info
n/a
Prepare for 5.0.0 release
n/a
=> doc: formatting and 5.0.0

plugin.xml
Update plugin.xml to 5.0.0
n/a
prepare for 5.0.0 release
n/a
=> chore: bump plugin.xml to 5.0.0

docs/PAYLOAD.md
Update link to the iOS Payload doc.
Resolves #190 
Fix the link of the iOS payload docs to point to the current and active docs.
=> doc: update link to iOS payload keys

src/ios/PushPlugin.m
Resolve the issue where updated configurations that require permission to be requested for.
Update the `handleNotificationSettingsWithAuthorizationOptions` method.
1. On first install when `authorizationStatus  == UNAuthorizationStatusNotDetermined` it should request for permissions based on the provided `UNAuthorizationOptions`
2. On app updates, calculate the permission differences between what is set in app initialize object and the currentGrantedOptions. Request for permissions that are missing. 
Resolves #127 
- Set permission `alert`, `badge`, and `sound`
- Built app
- Ran App
- Approved permission
- Update permissions to include `critical` & setting entitlements plist
- Build app
- Ran App
- Approve permission dialog for critical permission.
In the above steps, I do not uninstall …
=> fix(ios): request new permissions based on ios config changes

types/index.d.ts
Update typing.
- Added comments
- Added missing `forceShow` option to iOS
n/a
n/a
=> chore(*): updated typings - comments & iOS forceShow option

src/android/com/adobe/phonegap/push/PushPlugin.kt
This PR aims to catch all exceptions that could be thrown by the Firebase SDK.
fixes #340
This change allows us to catch all exceptions, thus eliminating potential crashes. Since deploying this code in production, all crashes have been resolved.
This code has been tested in local and deployed in production.
=> fix(android): catch all Firebase exceptions

package-lock.json
Rebuilt `package-lock.json`
n/a
Apply #348 changes and also rebuild `pacakge-lock.json`
Closes #348
=> chore(npm): rebuild package-lock.json

src/android/com/adobe/phonegap/push/PushPlugin.kt
Moved the token variable setting block slightly higher. This also de-indented the try/catch logic. The setting of token block has its own try/catch.
- Reducing nested try/catch.
- Clean up the exception block and improve the logging to print the exception type when fetching the token.
- Handle token errors slightly early before other logic.
- Built Cordova App
- Confirm token fetched
- Tested a case with incorrect key/appid in `google-service.json`
=> chore: move token higher and cleanup exception block
